In [6]:
import numpy as np

# Creating two 3x3 matrices using random function
matrix1 = np.random.random((3, 3))
matrix2 = np.random.random((3, 3))

# Performing the operations
product = np.prod(matrix1)  # Product (prod) of all elements in matrix1
multiplication = np.multiply(matrix1, matrix2)  # Element-wise multiplication
dot_product = np.dot(matrix1, matrix2)  # Dot product

# Printing the results
print("Product (prod):")
print(product)
print("\nMultiplication (multiply):")
print(multiplication)
print("\nDot Product (dot):")
print(dot_product)

Product (prod):
0.002780019770783062

Multiplication (multiply):
[[0.35786506 0.07082871 0.05194582]
 [0.07103165 0.69114687 0.64449619]
 [0.30826724 0.12187481 0.08587759]]

Dot Product (dot):
[[0.79132155 0.46458682 0.38105376]
 [0.90899244 0.92069323 1.06792795]
 [0.89982236 0.66329244 0.68432687]]


In [7]:
import numpy as np

# Input arrays
arr1 = np.array([2, 4, 6, 8, 10, 12])
arr2 = np.array([3, 6, 9, 12, 15, 18])

# Union
union = np.union1d(arr1, arr2)
print("Union:", union)

# Intersection
intersection = np.intersect1d(arr1, arr2)
print("Intersection:", intersection)

# Set difference
difference = np.setdiff1d(arr1, arr2)
print("Set Difference (arr1 - arr2):", difference)

# XOR (exclusive OR)
xor = np.setxor1d(arr1, arr2)
print("XOR:", xor)

Union: [ 2  3  4  6  8  9 10 12 15 18]
Intersection: [ 6 12]
Set Difference (arr1 - arr2): [ 2  4  8 10]
XOR: [ 2  3  4  8  9 10 15 18]


In [8]:
import numpy as np

# Creating a 1D array using Random function
array = np.random.rand(10)  # Change the size as per your requirement
print("Array:", array)

# Cumulative sum
cumulative_sum = np.cumsum(array)
print("Cumulative Sum:", cumulative_sum)

# Cumulative product
cumulative_product = np.cumprod(array)
print("Cumulative Product:", cumulative_product)

# Discrete difference with n=3
discrete_difference = np.diff(array, n=3)
print("Discrete Difference (n=3):", discrete_difference)

# Find unique elements from the array
unique_elements = np.unique(array)
print("Unique Elements:", unique_elements)

Array: [0.12001898 0.64442408 0.33352266 0.5893706  0.24792398 0.51561245
 0.98070647 0.36354353 0.08209573 0.13188439]
Cumulative Sum: [0.12001898 0.76444306 1.09796573 1.68733633 1.93526031 2.45087276
 3.43157923 3.79512275 3.87721848 4.00910287]
Cumulative Product: [1.20018980e-01 7.73431214e-02 2.57956839e-02 1.52032176e-02
 3.76924227e-03 1.94346823e-03 1.90597188e-03 6.92903736e-04
 5.68844356e-05 7.50216909e-06]
Discrete Difference (n=3): [ 1.40205587 -1.1640439   1.20642962 -0.41172952 -1.27966253  1.41797212
 -0.00447868]
Unique Elements: [0.08209573 0.12001898 0.13188439 0.24792398 0.33352266 0.36354353
 0.51561245 0.5893706  0.64442408 0.98070647]


In [9]:
import numpy as np

# Creating two 1D arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

# Addition using zip()
result_zip = [x + y for x, y in zip(arr1, arr2)]
print("Addition using zip():", result_zip)

# Addition using np.add()
result_np_add = np.add(arr1, arr2)
print("Addition using np.add():", result_np_add)

# Addition using np.frompyfunc()
add_func = np.frompyfunc(lambda x, y: x + y, 2, 1)
result_frompyfunc = add_func(arr1, arr2)
print("Addition using np.frompyfunc():", result_frompyfunc)

Addition using zip(): [7, 9, 11, 13, 15]
Addition using np.add(): [ 7  9 11 13 15]
Addition using np.frompyfunc(): [7 9 11 13 15]


In [12]:
import numpy as np

arr = np.array([4, 5, 7, 9, 10])

x1 = np.lcm.reduce(arr)
print("LCM of all elements in the array is: ", x1)

x2 = np.gcd.reduce(arr)
print("GCD of all elements in the array is: ", x2)

LCM of all elements in the array is:  1260
GCD of all elements in the array is:  1
